# Uncomment the next line to define a global platform for your project
# platform :ios, '15.2'

target 'PhotosSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotosSearch
pod 'SDWebImage', '~> 5.0'
`warn_for_unused_master_specs_repo => false`

end
